# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180723_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='belongs_to',
        ),
    ]
