# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180720_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='belongs_to',
            new_name='username',
        ),
    ]
