# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_remove_profile_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
