# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 12:27
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
