# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20180725_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_comments',
            field=models.ManyToManyField(default=False, to='insta.Profile'),
        ),
    ]
