# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_image_image_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_comments',
        ),
    ]
