# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_auto_20180725_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_comments',
        ),
    ]
