# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_remove_image_image_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(to='insta.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='insta.Image'),
        ),
    ]
