# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_auto_20180726_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
            preserve_default=False,
        ),
    ]
