# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0017_auto_20180726_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=0),
        ),
    ]
