# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0018_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=0, max_length=33),
        ),
    ]
